import HeroSection from '@/components/homeComponents/HeroSection'
import Head from 'next/head'

export default function Home() {
  return (
    <>
      <Head>
        <title>Orion Ux labs</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main >
        <div className="container-fluid p-0 m-0">
          <HeroSection />
        </div>
      </main>
    </>
  )
}